FROM golang:1.18.3

WORKDIR /usr/src/app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY ./Server/go.mod ./Server/go.sum ./
RUN go mod download && go mod verify

COPY ./ServerD .
RUN go build -v -o /usr/local/bin/app ./...

CMD ["app"]